'use client'

import { SubAppLayout } from '@/components/sub-app-layout'
import { NISTTestRunner } from './components/nist-test-runner'

export default function NISTTestsPage() {
  return (
    <SubAppLayout
      title="NIST Test Suite"
      description="Run NIST SP 800-22 statistical tests on entropy generated by Recursive Folding to verify randomness quality."
    >
      <NISTTestRunner />
    </SubAppLayout>
  )
}
